apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: eses5.azurecr.io/apigateway:latest
          env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: apigateway
  ports:
  - name: apigateway
    protocol: TCP
    port: 80
    targetPort: 80