kubectl apply -f apigateway-depl.yaml
kubectl apply -f authservice-depl.yaml
kubectl apply -f ingress-srv.yaml
kubectl apply -f inventory-depl.yaml
kubectl apply -f local-pvc.yaml
kubectl apply -f mssql-depl.yaml
kubectl apply -f order-depl.yaml
kubectl apply -f product-depl.yaml
kubectl apply -f rabbitmq-depl.yaml