apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: eses5.azurecr.io/authservice:latest
          env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_SERVER
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 80