apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventorymanagementservice
  template:
    metadata:
      labels:
        app: inventorymanagementservice
    spec:
      containers:
        - name: inventorymanagementservice
          image: eses5.azurecr.io/inventorymanagementsystem:latest
          env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_SERVER
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: inventorymanagementservice
  ports:
  - name: inventorymanagementservice
    protocol: TCP
    port: 80
    targetPort: 80