apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagementservice
  template:
    metadata:
      labels:
        app: ordermanagementservice
    spec:
      containers:
        - name: ordermanagementservice
          image: eses5.azurecr.io/ordermanagementsystem:latest
          env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_SERVER
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: ordermanagementservice
  ports:
  - name: ordermanagementservice
    protocol: TCP
    port: 80
    targetPort: 80