apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productmanagementservice
  template:
    metadata:
      labels:
        app: productmanagementservice
    spec:
      containers:
        - name: productmanagementservice
          image: eses5.azurecr.io/productmanagementsystem:latest
          env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_SERVER
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-conn
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: product-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: productmanagementservice
  ports:
  - name: productmanagementservice
    protocol: TCP
    port: 80
    targetPort: 80