apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productmanagementservice
  template:
    metadata:
      labels:
        app: productmanagementservice
    spec:
      containers:
        - name: productmanagementservice
          image: larsvandriel/productmanagementsystem:latest
          env:
          - name: SqlServer
            valueFrom:
              secretKeyRef:
                name: mssql-pms
                key: CONN_STRING
          - name: RabbitMQHost
            valueFrom:
              secretKeyRef:
                name: rabbitmq-host
                key: RABBITMQ_HOST
          - name: RabbitMQPort
            valueFrom:
              secretKeyRef:
                name: rabbitmq-port
                key: RABBITMQ_PORT
          - name: RabbitMQUser
            valueFrom:
              secretKeyRef:
                name: rabbitmq-user
                key: RABBITMQ_USER
          - name: RabbitMQPassword
            valueFrom:
              secretKeyRef:
                name: rabbitmq-pw
                key: RABBITMQ_PW
---
apiVersion: v1
kind: Service
metadata:
  name: product-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: productmanagementservice
  ports:
  - name: productmanagementservice
    protocol: TCP
    port: 80
    targetPort: 80